In [72]:
import numpy as np

### Esercizio 1
__Scrivete un array `val` di 101 numeri reali equidistanti compresi fra -1 e 1 inclusi. Costruite una funzione, `fun(x,n1,n2)`, che restituisca l'array dei valori della funzione
$\,y(x) = (x^{n1} + n2)\,e^{-x}\,$ in tutti i punti dell'array `x`. Usate `fun` per calcolare i valori di 
$ \,(x^3 -2) \,e^{-x}$ nei punti contenuti in `val`.__

In [73]:
#Creazione dell'array [-1, 1] con punti equidistanti
val = np.linspace(-1, 1, 101)

#Definizione della funzione fun
def fun(x, n1, n2):
    return (x**n1 + n2)*np.exp(-x)

#Test della funzione (stampa dei risultati)
fun(val, 3, -2)

array([-8.15484549, -7.83667738, -7.53405484, -7.24624244, -6.9725351 ,
       -6.71225689, -6.46476006, -6.22942393, -6.00565393, -5.79288063,
       -5.59055881, -5.39816656, -5.21520438, -5.0411944 , -4.87567951,
       -4.71822259, -4.56840579, -4.42582973, -4.29011284, -4.16089069,
       -4.03781526, -3.92055439, -3.8087911 , -3.70222303, -3.60056184,
       -3.5035327 , -3.4108737 , -3.3223354 , -3.23768025, -3.1566822 ,
       -3.07912618, -3.00480766, -2.93353225, -2.86511524, -2.79938125,
       -2.7361638 , -2.67530497, -2.61665502, -2.56007205, -2.50542169,
       -2.45257674, -2.4014169 , -2.35182844, -2.30370395, -2.25694202,
       -2.21144701, -2.16712878, -2.12390245, -2.08168816, -2.04041084,
       -2.        , -1.96038951, -1.92151739, -1.88332565, -1.84576006,
       -1.80877   , -1.77230827, -1.73633095, -1.7007972 , -1.66566913,
       -1.63091166, -1.59649238, -1.56238138, -1.52855117, -1.49497652,
       -1.46163435, -1.42850362, -1.39556522, -1.36280187, -1.33

### Esercizio 2
__Costruite l'array `a1` degli interi fra 0 e 100 incluso. Estraete da `a1` l'array `a2` dei valori `k` per cui 0.2 < sin(k) < 0.75. Costruite l'array `a3` delle radici quadrate dei valori in `a2`.__ 

In [74]:
#Creazione dell'array 1
a1 = np.arange(0, 101)
a1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [75]:
#Creazione dell'array 2
a2 = a1[np.logical_and(np.sin(a1) > 0.2, np.sin(a1) < 0.75)]
a2

array([ 7,  9, 13, 15, 28, 32, 34, 38, 40, 51, 53, 57, 59, 72, 76, 78, 82,
       84, 95, 97])

In [76]:
#Creazione dell'array 3
a3 = np.sqrt(a2)
a3

array([2.64575131, 3.        , 3.60555128, 3.87298335, 5.29150262,
       5.65685425, 5.83095189, 6.164414  , 6.32455532, 7.14142843,
       7.28010989, 7.54983444, 7.68114575, 8.48528137, 8.71779789,
       8.83176087, 9.05538514, 9.16515139, 9.74679434, 9.8488578 ])

### Esercizio 3
__Una tazza di corn flakes, un bicchiere di latte e un uovo forniscono 16 grammi di proteine. Un bicchiere di latte e due uova forniscono 21 grammi di proteine. Due tazze di corn flakes e due bicchieri di latte forniscono 16 grammi di proteine.
Quante proteine ciascuno contengono una tazza di corn flakes, un bicchiere di latte e un uovo?__

In [77]:
#Risoluzione del sistema lineare:

#x = corn flakes; y = latte; z = uovo; 

#{ x + y + z = 16
#{ y + 2z = 21
#{ 2x + 2y = 16

#Matrice dei coefficienti
A = np.array([
        [1, 1, 1],
        [0, 1, 2],
        [2, 2, 0]
])

#Vettore dei termini noti
B = np.array([16, 21, 16])

#Vettore delle incognite (trovato tramte risoluzione del sistema lineare)
#np.linalg.solve callcola la matrice inversa e fa il prodotto tra Ainv e B
X = np.linalg.solve(A, B)

#Valori delle proteine
print(f"{' '*10}{'Tazza di corn flakes':^22} {'Bicchiere di latte':^22} {'Uovo':^22}")
print("Proteine: ", end="")
for inc in X:
    print(f"{inc:^22} ", end="")

           Tazza di corn flakes    Bicchiere di latte            Uovo         
Proteine:          3.0                    5.0                    8.0           

In [78]:
#Verifica delle soluzioni
#[(a, b)] --> a = termine noto originale; b = verifica del termine noto
list(zip(B, np.dot(A, X)))

[(16, 16.0), (21, 21.0), (16, 16.0)]

### Esercizio 4
__Scrivete una funzione `ff(x,reverse=False)` che dato un array `x` restituica l'array `x2` dell'esponenziale dei valori in `x`.  Se `reverse=False` `ff` deve restituire `x2` con i valori in ordine crescente, se `reverse=True` `ff` deve restituire `x2` con i valori in ordine decrescente .__<BR>
__Testate `ff` su `np.array([-2,1,-0.1,4.2,0,1.2,-0.5,0.4,-1.3])`.__

In [79]:
#definizione della funzione ff
def ff(x, reverse=False):
    x2 = np.exp(x)
    
    #L'array va ordinato in ogni caso (per evitare di mettere in ordine decrescente elementi che non erano in ordine crescente)
    x2 = np.sort(x2)
    
    if reverse == True:
        x2 = np.flip(x2, axis=0)
        
    return x2

test_array = np.array([-2,1,-0.1,4.2,0,1.2,-0.5,0.4,-1.3])

ff(test_array)

array([ 0.13533528,  0.27253179,  0.60653066,  0.90483742,  1.        ,
        1.4918247 ,  2.71828183,  3.32011692, 66.68633104])

In [80]:
ff(test_array, reverse=True)

array([66.68633104,  3.32011692,  2.71828183,  1.4918247 ,  1.        ,
        0.90483742,  0.60653066,  0.27253179,  0.13533528])